// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/yadore-publisher-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"conversion_detail | conversion_detail_merchant | conversion_general | conversion_status | deeplink | deeplink_merchant | dnt | market | merchant | offer | report_detail | report_general | report_modified | report_status"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.YadorePublisherSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "yadore-publisher_list",
		Description: "List records from YadorePublisher. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "yadore-publisher_load",
		Description: "Load a single record from YadorePublisher. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.YadorePublisherSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.YadorePublisherSDK, name string) (sdk.YadorePublisherEntity, error) {
	switch strings.ToLower(name) {
	case "conversion_detail":
		return client.ConversionDetail(nil), nil
	case "conversion_detail_merchant":
		return client.ConversionDetailMerchant(nil), nil
	case "conversion_general":
		return client.ConversionGeneral(nil), nil
	case "conversion_status":
		return client.ConversionStatus(nil), nil
	case "deeplink":
		return client.Deeplink(nil), nil
	case "deeplink_merchant":
		return client.DeeplinkMerchant(nil), nil
	case "dnt":
		return client.Dnt(nil), nil
	case "market":
		return client.Market(nil), nil
	case "merchant":
		return client.Merchant(nil), nil
	case "offer":
		return client.Offer(nil), nil
	case "report_detail":
		return client.ReportDetail(nil), nil
	case "report_general":
		return client.ReportGeneral(nil), nil
	case "report_modified":
		return client.ReportModified(nil), nil
	case "report_status":
		return client.ReportStatus(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
